[phases.setup]
nixPkgs = ["python312", "cmake", "pkg-config", "gcc"]

[phases.install]
cmds = [
    "pip install --no-cache-dir --upgrade pip setuptools wheel",
    "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "python main.py"

