[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "cmake", "pkg-config", "gcc", "gnumake", "ninja-build", "binutils"]

[phases.install]
cmds = [
    "python3 -m venv /opt/venv",
    ". /opt/venv/bin/activate && pip install --no-cache-dir --upgrade pip setuptools wheel",
    ". /opt/venv/bin/activate && pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "/opt/venv/bin/python3 main.py"

