[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "cmake", "pkg-config", "gcc"]

[phases.install]
cmds = [
    "python3 -m pip install --no-cache-dir --upgrade pip setuptools wheel",
    "python3 -m pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "python3 main.py"

